version: "3.8"

services:
  myapp:
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3307/employee_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - mysql-db
    # Optionally, you can add a wait-for-it script to wait for MySQL
    entrypoint: ["java", "-jar", "/app/myapp.jar"]

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: employee_db
    ports:
      - "3307:3307"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=pass"]
      interval: 10s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

